// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarriorsAndMagesRPG.Infrastructure;

#nullable disable

namespace WarriorsAndMagesRPG.Infrastructure.Migrations
{
    [DbContext(typeof(WarriorsAndMagesContext))]
    partial class WarriorsAndMagesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarriorsAndMagesRPG.Infrastructure.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Identity key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .HasColumnType("int")
                        .HasComment("Character agility");

                    b.Property<int>("CharacterClass")
                        .HasColumnType("int")
                        .HasComment("Character class enum");

                    b.Property<string>("CharacterSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasComment("Character symbol");

                    b.Property<int>("Damage")
                        .HasColumnType("int")
                        .HasComment("Character damage");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasComment("Date of character creation");

                    b.Property<int>("Health")
                        .HasColumnType("int")
                        .HasComment("Character health");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int")
                        .HasComment("Character intelligence");

                    b.Property<int>("Range")
                        .HasColumnType("int")
                        .HasComment("Character range");

                    b.Property<int>("Strength")
                        .HasColumnType("int")
                        .HasComment("Character strength");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
